name: Java Docker Continuous Integration Workflow

on: [push]

jobs:
  # see https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven
  build:
    name: Create Maven Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

  # see https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Package
      - name: Display structure of downloaded files
        run: ls -R
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag codecop/ticketmagpie:latest
      - name: Push the latest Docker image to Docker Hub
        run: docker push codecop/ticketmagpie:latest
